### ISSUE TITLE
Chance of miss, cirt, and heavy?

### ISSUE THREAD

**Issue by eight04** [eight04/mgcm-skill-data#11]
The official how-to is not clear. Following are my assumptions:

*Natural*
```yml
Miss: 0
Crit: 0.3
Heavy: 0
```

*Superior*
```yml
Miss: 0
Crit: 0.3+0.15 = 0.45 # should it be 0.3*1.15 = 0.345?
Heavy: (1-0.45)*0.3 = 0.165
```

*Inferior*
```yml
Miss: 0.5
Crit: (1-0.5)*(0.3-0.15) = 0.075 # should it be (1-0.5)*(0.3*0.85) = 0.1275?
Heavy: 0
```

**Comment by eight04** [comment]
Also how does crit rate passive/buff work?

**Comment by homu-gamepress** [comment]
This is our best understanding after discussing with the English playerbase:

1. Crit stacking: additive

This is evident from nobody ever witnessed Arachne Iroha failing to crit against neutral targets with her skill 2 (30%+20%+50%).  We infer this is also true for element advantage (30%+15%) and disadvantage (30%-15%).

2. Heavy Blow

> Critical Hit and Heavy Blow cannot activate at the same time, and Critical Hit will take priority.

from: https://api.magicami.johren.games/SubContents/HowToDetail?categoryId=7&id=7_5

We infer that crit and heavy blow are independent rolls, with crit having priority when both true.

3. Misses

We presume misses are rolled first.

**Comment by spliffm** [comment]
I think this is already what you arrived at but just to reiterate:

_Neutral_

```yaml
Miss: 0
Crit: 0.3
Heavy: 0
```

_Superior_

```yaml
Miss: 0
Crit: 0.3 + 0.15 = 0.45
Heavy: 0.3
```

_Inferior_

```yaml
Miss: 0.5
Crit: 0.3 - 0.15 = 0.15
Heavy: 0
```

Since miss takes priority over crit and crit takes priority over heavy blows you can assume that for all values
```javascript
crit = min(1 - miss, crit)
heavy = min(1 - miss - crit, heavy)
```

Essentially it is a single roll system.
